export const TAG_TYPE = {
  ME: 'ME',
  ORGANIZATION: 'ORGANIZATION',
  SLICE: 'SLICE',
  SLICES: 'SLICES',
  SPACES: 'SPACES',
  WORKSPACES: 'WORKSPACES',
  WORKSPACE: 'WORKSPACE',
  SUBSCRIPTIONS: 'SUBSCRIPTIONS',
  AI_GENERATE: 'AI_GENERATE',
  AI_TRANSCRIPTION: 'AI_TRANSCRIPTION',
} as const;

export type TagType = (typeof TAG_TYPE)[keyof typeof TAG_TYPE];
